execute: 
  cache: false
  freeze: false
  message: false
  warning: false

project:
  type: website
  output-dir: docs
  execute-dir: project
  render: 
    - code/index.qmd
    - code/*.qmd

format:
  html:
    toc: true
    toc-depth: 4
    code-fold: false
    standalone: true
    embed-resources: true
    bibliography: code/_.bib

website:
  title: "SpatialData"
  navbar:
    left:
      - code/csama.qmd
      - code/fractal.qmd
      - code/merfish.qmd
      - code/mibitof.qmd
      - code/mcmicro.qmd
      - code/cosmx.qmd
      - code/xenium.qmd
      - code/visium.qmd
      - code/visiumhd.qmd
